### ISSUE TITLE
簡単なCSSファイルの作成

### ISSUE THREAD

**Issue by W-Hidetoshi** [W-Hidetoshi/tutorial_0605#1]
## 簡単なCSSファイルの作成

- CSSファイルを作り、HTMLファイルを見やすくしていく。

**Comment by W-Hidetoshi** [comment]
```css
/*css-file */
@charset "UTF-8";

body{
    background-color: aqua;
}
```
