### ISSUE TITLE
htmlファイルのコンテンツを増やす

### ISSUE THREAD

**Issue by W-Hidetoshi** [W-Hidetoshi/tutorial_0605#2]
### プロフィールページの作成

掲載内容

- 名前
- 出身地
- 趣味・特技
- 最後に一言

### 現在の状況について

```html
<!DOCTYPE html>
<html>
    <head>
        <title>テストページ</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        Hello, Git.<br>
        <h1>こんにちはー！</h1>
        <p>今日の天気はいかがでしょうか。</p>
    </body>
</html>
``` 

```css
/*css-file */
@charset "UTF-8";

body{
    background-color: aqua;
}
```
